"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useAppSelector } from "@/redux/hook";
import { Provider } from "react-redux";
import { store } from "@/redux/store";

const inter = Inter({ subsets: ["latin"] });

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={store}>
      <RootContent>{children}</RootContent>
    </Provider>
  );
}

function RootContent({ children }: { children: React.ReactNode }) {
  const darkMode = useAppSelector((state) => state.theme.darkMode);
  console.log(darkMode);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          className={`${
            darkMode ? "text-white bg-black" : "text-black bg-white"
          }`}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
