"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useAppSelector } from "@/redux/hook";
import { Provider } from "react-redux";
import { persistor, store } from "@/redux/store";
import { PersistGate } from 'redux-persist/integration/react'

const inter = Inter({ subsets: ["latin"] });

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={store}>
            {/* <PersistGate loading={null} persistor={persistor}> */}

      <RootContent>{children}</RootContent>
      {/* </PersistGate> */}
    </Provider>
  );
}

function RootContent({ children }: { children: React.ReactNode }) {
  const darkMode = useAppSelector((state) => state.theme.darkMode);
  // console.log(darkMode);
  return (
    <html lang="en">
      <body className={inter.className}   >
        <div
          className={`${
            darkMode ? "text-white bg-slate-400" : "text-black bg-white"
          }`}
          style={{ overflow: "auto" }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
