"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useAppSelector } from "@/redux/hook";
import { Provider } from "react-redux";
import { persistor, store } from "@/redux/store";
import { PersistGate } from 'redux-persist/integration/react'
import { ToastContainer } from "react-toastify";

// const inter = Inter({ subsets: ["latin"] });

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={store}>
            {/* <PersistGate loading={null} persistor={persistor}> */}

      <RootContent>{children}</RootContent>
      {/* </PersistGate> */}
    </Provider>
  );
}

function RootContent({ children }: { children: React.ReactNode }) {
  // const darkMode = useAppSelector((state) => state.theme.darkMode);
  // console.log(darkMode);
  const themeColor=useAppSelector((state)=>state.theme.themeColor)
  console.log(themeColor)
  return (
    <html lang="en">
      <body    >
        <div
         
          style={{backgroundColor:themeColor}}
        >
           <ToastContainer />
          {children}
        </div>
      </body>
    </html>
  );
}